#!/bin/bash
sudo docker build -t test_mountainlab .

args="$@ --net=host --pid=host"

args="$args --rm -e DISPLAY=$DISPLAY"

useradd_cmd="useradd -d /home/mluser -u $UID mluser; chown -R mluser:mluser /home/mluser"

#Here's an example of making the home directory available
#args="$args -v $HOME:/home/mluser"

args="$args -v /tmp/.X11-unix:/tmp/.X11-unix"

args="$args -it test_mountainlab /bin/bash -c '$useradd_cmd; su - mluser -c '/bin/bash''"

echo sudo docker run $args
/bin/bash -c "sudo docker run $args"