#!/bin/bash
sudo docker build -t test_mountainlab .
exit_code=$?

if [ $exit_code -ne 0 ];then
   exit $exit_code
fi

args="$@ --net=host --pid=host"

args="$args --rm -e DISPLAY=$DISPLAY"

useradd_cmd="useradd -d /home/mluser -u $UID mluser; chown -R mluser:mluser /home/mluser"

#Here's an example of making the home directory available
#args="$args -v $HOME:/home/mluser"

args="$args -v /tmp/.X11-unix:/tmp/.X11-unix"

cmds_to_run="cd /home/mluser/dev/mountainlab;"
cmds_to_run="$cmds_to_run echo asjdkajsdlajksd;"
cmds_to_run="$cmds_to_run export PATH=~/dev/mountainlab/bin:\$PATH"

args="$args -it test_mountainlab /bin/bash -c '$useradd_cmd && echo \"$cmds_to_run\" > /home/mluser/.bashrc && su - mluser -c '/bin/bash''"

echo sudo docker run $args
/bin/bash -c "sudo docker run $args"
