#!/usr/bin/env node

function print_usage() {
	console.log ('kron_view [view_program_name] [pipeline_name] [dataset_name] --outpath=[output(default)]');
	console.log ('kron_view [view_program_name] [dataset_name] --outpath=[output(default)]');
}

var fs=require('fs');
var common=require(__dirname+'/common.node.js');

var CLP=new common.CLParams(process.argv);

var view_program_name=CLP.unnamedParameters[0];
var pipname=CLP.unnamedParameters[1];
var dsname=CLP.unnamedParameters[2];
if (CLP.unnamedParameters.length==2) {
	pipname='';
	dsname=CLP.unnamedParameters[1];
}
var outpath=CLP.namedParameters.outpath||'output';
var pipelines_path='pipelines.txt';
var datasets_path='datasets.txt';

if ((!dsname)||(!outpath)||(!pipelines_path)||(!datasets_path)) {
	print_usage();
	process.exit(-1);
}

var datasets=common.read_datasets_from_text_file(datasets_path);
var dataset=common.find_dataset(datasets,dsname);

if (!dataset) {
	console.log ('Unable to find dataset: '+dsname);
	process.exit(-1);
}

var view_program_file=common.find_view_program_file(view_program_name);
if (!view_program_file) {
	console.log ('Unable to find view program: '+view_program_name);
	process.exit(-1);	
}

var output_folder='';
if (pipname) output_folder=outpath+'/'+pipname+'--'+dsname;

var args='';
for (var key in CLP.namedParameters) {
	args+=' --'+key+'='+CLP.namedParameters[key];
}
args+=' --dataset_folder='+dataset.absolute_folder_path;
if (output_folder) {
	args+=' --output_folder='+output_folder;
}
args=args.split(' ');
common.make_system_call(view_program_file,args,function() {
});

common.wait_for_system_calls_to_finish(function() {
});
