%ISOCUT - 
%
% Syntax:  [cutpoint] = isocut(X, threshold)
%
% Inputs:
%    threshold - double
%    X - double (1,N)
%
% Outputs:
%    cutpoint - double (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
